// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQkvJ_uTiC5KmEgy-JZVB5heUm7mJ1HA',
    appId: '1:1053611822289:web:09df908b74684c9ce289f0',
    messagingSenderId: '1053611822289',
    projectId: 'flashcards-app-4f17c',
    authDomain: 'flashcards-app-4f17c.firebaseapp.com',
    storageBucket: 'flashcards-app-4f17c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1ewTMGwik1P2ymKKwCwaln9jeVCGM0I',
    appId: '1:1053611822289:android:4f2aea8d4a3fb1bbe289f0',
    messagingSenderId: '1053611822289',
    projectId: 'flashcards-app-4f17c',
    storageBucket: 'flashcards-app-4f17c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQkvJ_uTiC5KmEgy-JZVB5heUm7mJ1HA',
    appId: '1:1053611822289:web:f647eab7ab7d87ffe289f0',
    messagingSenderId: '1053611822289',
    projectId: 'flashcards-app-4f17c',
    authDomain: 'flashcards-app-4f17c.firebaseapp.com',
    storageBucket: 'flashcards-app-4f17c.firebasestorage.app',
  );
}
